-- H2 schema for orders and order line items.

--CREATE TABLE IF NOT EXISTS tenants (
--  tenant_id VARCHAR(64) PRIMARY KEY,
--  name VARCHAR(255) NOT NULL UNIQUE,
--  created_time TIMESTAMP NOT NULL,
--  updated_time TIMESTAMP NOT NULL
--);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  order_id VARCHAR(64) NOT NULL,
  customer_id VARCHAR(64),
  status VARCHAR(32) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  total_amount DOUBLE PRECISION NOT NULL,
  created_time TIMESTAMP NOT NULL,
  updated_time TIMESTAMP NOT NULL
--  CONSTRAINT fk_orders_tenant
--    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_pk BIGINT NOT NULL,
  sku VARCHAR(128) NOT NULL,
  name VARCHAR(255),
  quantity INTEGER NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL,
  CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_pk) REFERENCES orders(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_orders_tenant_id ON orders(tenant_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON orders(order_id);

