FROM eclipse-temurin:25-jdk

WORKDIR /app

# Create non-root user
RUN addgroup --system spring && adduser --system spring --ingroup spring
USER spring:spring

COPY build/libs/order-service-app-0.0.1-SNAPSHOT.jar app.jar

ENV SPRING_PROFILES_ACTIVE=docker

EXPOSE 8080
EXPOSE 9094

ENTRYPOINT ["java", "-jar", "app.jar"]
